site_name: Home Assistant User Guide

nav:
  - Home: index.md
  - Installation: docs/installation.md
  - Configuration: docs/configuration.md
  - Automation: docs/automation.md
  - Troubleshooting: docs/troubleshooting.md

theme:
  name: material
