site_name: Home Assistant User Guide
nav:
  - Home: index.md
  - Installation: docs/installation.md
  - Configuration: docs/configuration.md
  - Automation: docs/automation.md
  - Troubleshooting: docs/troubleshooting.md

theme:
  name: material  # Professional theme for software documentation

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      baselevel: 2
